### ISSUE TITLE
Adding static pages to homepage

### ISSUE THREAD

**Issue by baronvonbirra** [charlieasemota/philomina-wp#1]
There seems to be no way to post static pages on homepage, just "latest posts" or a specific page, right? or I am missing something? 

Good job by the way.

**Comment by charlieasemota** [comment]
@baronvonbirra not out of the box unless you want to change the loop query. Maybe this could help: http://stackoverflow.com/questions/196505/using-wordpress-loop-with-pages-instead-of-posts

**Comment by baronvonbirra** [comment]
Thanks for the response, @charlieasemota ! I'm very noob with coding in WP and although I didn't get a clear answer in the link you attached, it helped me out to find an answer. In case someone needs it, it's easy as pasting this at the beginning of "loop.php" code:

```
<?php // Retrieve only Pages and exclude About, links, contact, etc.
         $args = array(       // set up arguments
            'post_type' => 'page',              // Only Pages
             'post__not_in' => array(5)   // Do NOT show postID
                 );
       query_posts($args);   // execute the arguments
  ?>
```

Once again, thanks!
