### ISSUE TITLE
Remove tags from posts?

### ISSUE THREAD

**Issue by PhDResearchWebsite** [charlieasemota/philomina-wp#11]
Hello,

I was wondering if it's possible to remove the yellow banner for tags on posts? I haven't used the tags and was hoping that the yellow wouldn't show up.

Thanks for your time in answering this.

**Comment by CharlieCollabco** [comment]
@PhDResearchWebsite Hi, uhm at he moment there aren't really any custom options for the theme. If you know HTML you can edit it out for now.
As soon as i have time I will update the theme on the WordPress.org.
