### ISSUE TITLE
Scroll to right option loop?

### ISSUE THREAD

**Issue by socrspy** [charlieasemota/philomina-wp#12]
Is there any way i can add a scroll to right option? i want to be able to continue putting new posts in the loop but when i have more than 6 it will push the 7th down :)

**Comment by socrspy** [comment]
http://theabouwmaniconen.nl/ example :) if you scroll down you'll notice the 7th post is pushed down

**Comment by charlieasemota** [comment]
Hi @socrspy, there isn't an option in the theme for that, you'll need to go in the themes files and change the code or make a child theme sorry with your style customizations
