### ISSUE TITLE
Removing sidebar/full width posts

### ISSUE THREAD

**Issue by teamdisaster** [charlieasemota/philomina-wp#2]
I've removed all the sidebar widgets, but I cannot figure out how to remove the space that is still there. Any chance of adding a sidebar delete to a future update? Help me with some code to add with a CSS plug in? 

I love the theme, thank you. You've done a great job.

**Comment by charlieasemota** [comment]
HI @teamdisaster, you just need to change the width in the css if you want to modify the layout.
Or simply copy and paste the same code thats on page.php to single.php

**Comment by teamdisaster** [comment]
Thank you! I think I got it figured out now. I'm learning as I go and the help is much appreciated.
