### ISSUE TITLE
Link from a post to a page 

### ISSUE THREAD

**Issue by victorbarcelo** [charlieasemota/philomina-wp#3]
Hi! 

I would like to use the front page that present all the latest post as a menu. The problem is that instead of going to a post by clicking on "Continue" i would rather go to a page. 

Basically what Im trying to do is that, since you can only put the latest post as a static front page, link this post to a page. 

Im sure is something really simple, but I have 0 idea...  
Thanks a lot in advance! 
victor

**Comment by charlieasemota** [comment]
Hi @victorbarcelo I think what you're looking for was already answered here https://github.com/charlieasemota/philomina-wp/issues/1

**Comment by victorbarcelo** [comment]
Hi charlieasemota! Thanks a lot, it works!
