### ISSUE TITLE
Pages not loading–stuck on the loading viewer.

### ISSUE THREAD

**Issue by adminalec** [charlieasemota/philomina-wp#4]
Hi, I've been using this theme for about two months now and suddenly, whenever I click any of the options in my menus or landing page, the new pages take forever to load (sometimes even 1-2 minutes) or are just stuck there. What is going on and how can I fix it? Please let me know.
Here's the site I'm having issues with: www.alecnorris.com

**Comment by charlieasemota** [comment]
Hi @adminalec, it does that because the animation only ends when every single bit of the page is loaded, what plugins do you use on the site?

**Comment by adminalec** [comment]
Hi again! Just disabled all plugins and re-activated one by one to see behavior. 
Everything got so much better! Looks like I had more than one lightbox style plugin running and some extra ones. I'll let you know if I run into issues again. Thank you so much for your reply!

**Comment by charlieasemota** [comment]
@adminalec Sweet!
