### ISSUE TITLE
Child Theme Published on GitHub

### ISSUE THREAD

**Issue by thursby** [charlieasemota/philomina-wp#6]
Hello Philominians,
I've been using Philomina on a client's site. I've created a child theme for my customizations, so I figured I'd go ahead and publish it just in case there was any interest.

https://github.com/thursby/philomina-wp-child

The WordPress site is up and running over at http://www.sherriefindsfashion.com

Documentation is sparse at the moment, but soon I'll list the various changes it implements. Some highlights include:
- Removed "Continue" button and made the entire image clickable
- Added widget area to the bottom of the theme on home and posts.
- Changed the behavior of the images because all my images are cropped and sized before upload

PS. I'm a noob on GitHub, so maybe Issues is not the right place for this. Where else would I put it?

**Comment by charlieasemota** [comment]
@thursby hey man, looks good! I'd suggest you add a padding to the top of the footer and remove the margin top of the H3 to align them at the same vertical level ;)

**Comment by thursby** [comment]
Hey nice catch! The H3 issue was actually a bit of busted code in a MailPoet update. The newest version fixes it.

**Comment by gengiebattad78** [comment]
im just started and using this theme, do i need to DL plug ins of child them>?
and can u give me any procedure for this theme to follow pls. thanks

**Comment by charlieasemota** [comment]
@gengiebattad78 No you don't need any plugins or child themes if you want to instal the main theme. However you will need the original theme if you want to use the child theme.
