### ISSUE TITLE
Philomina-wp Tutorial

### ISSUE THREAD

**Issue by gengiebattad78** [charlieasemota/philomina-wp#7]
this is my first time to make a website. i just want to know only the basic procedure for this theme. How to upload the photos on screen with tag?
Thanks

**Comment by charlieasemota** [comment]
@gengiebattad78 Hi on the side of t=your edit page there is a box where you can select a featured image, that will be the one used as background while the post title will be displayed on it.

**Comment by minegra** [comment]
esta es mi primera vez para hacer un sitio web. Sólo quiero saber sólo el procedimiento básico para este tema. Cómo enlazar las fotos en la pantalla con la etiqueta a una pagina del menu? 
Gracias

**Comment by charlieasemota** [comment]
@minegra sorry?

**Comment by nahtee** [comment]
@charlieasemota minegra's post translated, "This is my first time to make a website. I just want to know just the basic procedure for this theme. How to link the photos on the screen with the label to a menu page? Thank you"
