### ISSUE TITLE
How to use website like the preview?

### ISSUE THREAD

**Issue by lacormick** [charlieasemota/philomina-wp#8]
Hello. I love how this theme looks. But since Wordpress changed their themes, whenever I install the theme, it looks nothing like the preview (the banner with the big images). How do you make this happen? Please help. thank you!

Is it a configuration option to select some kind of display form or something?

**Comment by charlieasemota** [comment]
Hi @lacormick, that is not a banner that's a list of posts with a featured images. If you go on the "create new post" section of your panel on the right side you'll find a box where you can select a featured image that will appear in the rectangle.

No there is no configuration for this theme. Thanks.
