### ISSUE TITLE
Navigation on the Fancybox

### ISSUE THREAD

**Issue by nahtee** [charlieasemota/philomina-wp#9]
GREAT THEME! Just one thing though...I use image galleries in my posts and I see that the Fancybox only has the "close" button and no navigation arrows.

How would I go about adding navigation functionality? Considering I use galleries, it would be tons more user-friendly to allow visitors to be able to "scroll" through the gallery.
...or...
If I can't add the functionality then how would I go about removing Fancybox COMPLETELY so I can use a lightbox plugin in its place? I added a lightbox plugin before posting this...I ended up with both fancy and light box popping up on top of each other.

Thank you!

**Comment by charlieasemota** [comment]
Hi nahtee, thanks for the feedback, haven't been following this project for a while, I added the feature and updated the files here, gonna be submitting it to the wordpress directory so hopefully everyone will have it updated soon.
